[package]
name = "nitro"
version = "0.1.0"
build = "build.rs"
authors = [
    "Jesse Maes <kebertyx@gmail.com>",
    "Aaron Hudson <aahud@cs.nmt.edu>"
]

[build-dependencies]
lalrpop = "0.13.1"

[dependencies]
lalrpop-util = "0.13.1"
regex = "0.2.1"